spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
  mvc:
    view:
      prefix: /view/
      suffix: .jsp